-- Written in the SQL subset shared by H2 and PostgreSQL.

CREATE TABLE room (
    id          VARCHAR(32)              NOT NULL PRIMARY KEY,
    name        VARCHAR(40)              NOT NULL,
    description VARCHAR(200)             NOT NULL,
    created_by  VARCHAR(20)              NOT NULL,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE chat_message (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    channel   VARCHAR(80)              NOT NULL,
    room_id   VARCHAR(32)              REFERENCES room (id),
    sender    VARCHAR(20)              NOT NULL,
    recipient VARCHAR(20),
    content   VARCHAR(4000)            NOT NULL,
    sent_at   TIMESTAMP WITH TIME ZONE NOT NULL
);

-- History pages: WHERE channel = ? AND id < ? ORDER BY id DESC
CREATE INDEX idx_chat_message_channel_id ON chat_message (channel, id);
-- Direct conversation list: WHERE recipient IS NOT NULL AND (sender = ? OR recipient = ?)
CREATE INDEX idx_chat_message_sender ON chat_message (sender, channel);
CREATE INDEX idx_chat_message_recipient ON chat_message (recipient, channel);

INSERT INTO room (id, name, description, created_by, created_at) VALUES
    ('general', 'General', 'Anything goes', 'system', CURRENT_TIMESTAMP),
    ('random', 'Random', 'Off-topic chatter', 'system', CURRENT_TIMESTAMP);
